Repository gunrock/gunrock, pull requests merged in 2018-08, with the labels that each got.

#368 Enabling cmake support for dev-refactor branch
  CMakeLists.txt
  cmake/FindRapidJson.cmake
  cmake/SetSubProject.cmake
  gunrock/CMakeLists.txt
  gunrock/app/app_base.cuh
  gunrock/app/pr/pr_app.cu
  gunrock/graph/coo.cuh
  gunrock/gunrock.h
  python/pagerank.py
  shared_lib_tests/CMakeLists.txt
  shared_lib_tests/shared_lib_pr.c
Labels: build issue

#371 TC run script added
  examples/tc/run.sh
Labels: release

#378 [dev-refactor] Betweenness Centrality port to new API.
  gunrock/app/Template/Template_app.cu
  gunrock/app/bc/bc_app.cu
  gunrock/app/bc/bc_enactor.cuh
  gunrock/app/bc/bc_functor.cuh
  gunrock/app/bc/bc_problem.cuh
  gunrock/app/bc/bc_test.cuh
  gunrock/app/enactor_iteration.cuh
  gunrock/app/pr/pr_enactor.cuh
  gunrock/app/pr/pr_problem.cuh
  gunrock/app/pr/pr_test.cuh
  gunrock/app/problem_base.cuh
  gunrock/graph/coo.cuh
  gunrock/oprtr/LB_advance/kernel.cuh
  gunrock/oprtr/advance/advance_base.cuh
  gunrock/oprtr/advance/kernel_policy.cuh
  gunrock/oprtr/filter/kernel_policy.cuh
  gunrock/oprtr/simplified2_filter/kernel_policy.cuh
  gunrock/oprtr/simplified_filter/kernel_policy.cuh
  tests/BaseMakefile.mk
  tests/bc/Makefile
  tests/bc/README.md
  tests/bc/run.sh
  tests/bc/run_real.sh
  tests/bc/test.sh
  tests/bc/test_bc.cu
  tests/pr/Makefile
  tests/pr/test_pr.cu
Labels: refactor
