Repository gunrock/gunrock, pull requests merged in 2019-06, with the labels that each got.

#541 [BFS] Refactored
  examples/CMakeLists.txt
  examples/bfs/Makefile
  examples/bfs/run.sh
  examples/bfs/run_do.sh
  examples/bfs/test_bfs.cu
  examples/sssp/Makefile
  gunrock/app/bfs/bfs_app.cu
  gunrock/app/bfs/bfs_enactor.cuh
  gunrock/app/bfs/bfs_functor.cuh
  gunrock/app/bfs/bfs_kernel.cuh
  gunrock/app/bfs/bfs_problem.cuh
  gunrock/app/bfs/bfs_test.cuh
  gunrock/app/frontier.cuh
  gunrock/app/sssp/sssp_app.cu
  gunrock/app/sssp/sssp_problem.cuh
  gunrock/app/test_base.cuh
  gunrock/graph/coo.cuh
  gunrock/graph/csc.cuh
  gunrock/gunrock.h
  gunrock/oprtr/1D_oprtr/for.cuh
  gunrock/oprtr/CULL_filter/cta.cuh
  gunrock/oprtr/CULL_filter/kernel_policy.cuh
  gunrock/oprtr/LB_CULL_advance/kernel.cuh
  gunrock/oprtr/LB_CULL_advance/kernel_policy.cuh
  gunrock/oprtr/compacted_cull_filter/cta.cuh
  gunrock/oprtr/compacted_cull_filter/kernel_policy.cuh
  gunrock/oprtr/oprtr.cuh
  gunrock/oprtr/oprtr_base.cuh
  gunrock/util/array_utils.cuh
  gunrock/util/cta_work_progress.cuh
  gunrock/util/device_intrinsics.cuh
  gunrock/util/error_utils.cu
  gunrock/util/error_utils.cuh
Labels: refactor

#549 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documents

#555 Add subgraph matching to pre-release
  dataset/small/tree.mtx
  examples/sm/Makefile
  examples/sm/run.sh
  examples/sm/sm_main.cu
  examples/ss/ss_main.cu
  gunrock/app/sm/sm_app.cu
  gunrock/app/sm/sm_enactor.cuh
  gunrock/app/sm/sm_problem.cuh
  gunrock/app/sm/sm_test.cuh
Labels: new primitive, refactor, release
